import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {ConfigProvider, Layout} from "antd";
import AppHeader from "@/components/AppHeader";
import Sider from "antd/es/layout/Sider";
import AppSideMenu from "@/components/AppSideMenu";
import {Content} from "antd/es/layout/layout";
import enUS from "antd/es/locale/en_US";
import '@ant-design/v5-patch-for-react-19';

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ConfigProvider locale={enUS}>
            <AntdRegistry>
                <Layout>
                    <AppHeader />
                    <Layout hasSider>
                        <Sider
                            theme="light"
                            style={{
                                position: "fixed",
                                top: "64px",
                                left: 0,
                                borderRight: "1px solid #f1f1f1",
                                height: "calc(100vh - 64px)",
                            }}
                        >
                            <AppSideMenu />
                        </Sider>
                        <Layout style={{ marginLeft: "200px" }}>
                            <Content
                                style={{ padding: "16px", minHeight: "calc(100vh - 64px)" }}
                            >
                                {" "}
                                {children}
                            </Content>
                        </Layout>
                    </Layout>
                </Layout>
            </AntdRegistry>
        </ConfigProvider>

        </body>
        </html>
    );
}